Add serializer deserializer class for JobSubmitMessage
NimbleEdge/RecoEdge pull request #102
Opened 2022-01-18 00:50 UTC by ruchirgarg05

Added class to serialize the JobSubmitMessage.

2022-01-18 05:27 UTC, ramesht007 commented on fedrec/serialization/test.py
> +import yaml
You can add this file inside the test folder in the root directory

2022-01-18 05:27 UTC, ramesht007 commented on fedrec/serialization/serializers.py
> +    workerstate data is pickled into the specified file, as workerstate might be
please fix the comment to match the PEP8 guidelines.

2022-01-20 11:51 UTC, vkkhare requested changes

2022-01-20 11:51 UTC, vkkhare commented on fedrec/serialization/test.py
> +with open("configs/dlrm_fl.yml", 'r') as cfg:
these tests should not be written like this. 
You can refer to the test folder to check if everything is working and how you can implement the kafka based testing

2022-02-17 10:25 UTC, closed without merging

2022-02-17 10:25 UTC, vkkhare commented
Needs to be adapted with the new code