Added Inline Documentation
NimbleEdge/RecoEdge pull request #126
Opened 2022-01-21 09:39 UTC by Viditagarwal7479

A possible fix for the issue "Documentation: Write Inline Documentation for train.py #93."

2022-01-21 10:02 UTC, ramesht007 requested changes
Please follow the [following](https://numpydoc.readthedocs.io/en/latest/format.html) style guide to write the documentation.

2022-01-22 10:41 UTC, vkkhare requested changes

2022-01-22 10:41 UTC, vkkhare commented on train.py
> +    arg_dict = vars(args) # convert to dict
Instead of writing comments for each line, you can follow sphinx style method descriptions describing the purpose and input and an example to use. Think of these like API docs.

2022-01-23 20:59 UTC, Viditagarwal7479 commented
Kindly review the updated file.

2022-01-26 09:37 UTC, vkkhare requested changes

2022-01-26 09:37 UTC, vkkhare commented on train.py
> +    :return: None
Check [these](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_numpy.html) guidelines for format. You can also look at the files in fedrec/communications to check examples

2022-01-26 09:38 UTC, vkkhare commented
Great going @Viditagarwal7479 the content looks good, just needs cosmetic restructuring

2022-01-26 10:34 UTC, ramesht007 commented on train.py
> +    updated configuration dictionary with arguments passed in command line
you can write it like this
```
:return: updated configuration dictionary
            with arguments passed in command line
```

2022-01-26 10:40 UTC, ramesht007 commented on train.py
> +    :raises:ValueError if no valid path to directory
There is space after this line. 
Can you check ?

2022-01-26 10:49 UTC, ramesht007 commented
Awesome Job @Viditagarwal7479 
Just very minor change.

2022-01-26 13:16 UTC, ramesht007 approved these changes

2022-01-26 15:44 UTC, vkkhare approved these changes

2022-01-26 15:46 UTC, merged