Feature/process manager
NimbleEdge/RecoEdge pull request #14
Opened 2021-07-24 16:46 UTC by harshv834

Fixes #9

2021-07-24 17:59 UTC, harshv834 commented on fedrec/multiprocessing/process_manager.py
> +            if len(self.enqueued_jobs) > 0:
Make enqueued_jobs into asyncio queue.

2021-07-24 17:59 UTC, harshv834 commented on fedrec/multiprocessing/process_manager.py
> +                        self.loop.stop()
Add all cancellation types.

2021-07-24 17:59 UTC, harshv834 commented on fedrec/multiprocessing/process_manager.py
> +        self.pool = MPI.COMM_WORLD
main process doesn't run process manager.

2021-07-24 17:59 UTC, harshv834 commented on fedrec/communications/process_com_manager.py
> +    async def receive_message(self,):
Tasks  ---
- Handle message like worker com manager
- Process-related messages write here.

2021-07-24 17:59 UTC, harshv834 commented on fedrec/multiprocessing/process_manager.py
> +    def balance_load(self):
Remove this from here.

2021-07-24 17:59 UTC, harshv834 commented on fedrec/multiprocessing/job.py
> +        print("here")
Format job type input and output according to PR #13

2021-08-17 11:34 UTC, vkkhare requested changes

2021-08-17 11:34 UTC, vkkhare commented on fedrec/communications/process_com_manager.py
> +@registry.load("process_comm_manager", "zeroMQ_process_comm_manager")
a shorter name will help ;p

2021-08-17 11:34 UTC, vkkhare commented on fedrec/communications/process_com_manager.py
> +@registry.load("process_comm_manager", "zeroMQ_process_comm_manager")
Btw why do we need a registry here? It's not doing anything specific to zeroMQ

2021-08-23 21:53 UTC, vkkhare commented on fedrec/multiprocessing/process_manager.py
> +            self.process_comm_manager = registry.construct("process_comm_manager", config_dict = config["comm_manager_config"])
Will process_com_manager be different from communication interfaces like zmq? If not we can probably subclass this to communication manager

2021-08-23 21:53 UTC, vkkhare commented on fedrec/multiprocessing/process_manager.py
> +    async def consume(self) -> None:
If we subclass this to communication manager, the consume could be independent or overriden accordingly

2021-09-12 19:35 UTC, vkkhare approved these changes

2021-09-12 19:36 UTC, merged