Inline documentation for test.py file added
NimbleEdge/RecoEdge pull request #140
Opened 2022-01-26 20:18 UTC by Kratos-is-here

2022-01-28 02:03 UTC, ramesht007 commented on test.py
> +        """The __init__ method lets the class initialize the objects attributes
Add ```Args``` above the init method.
and you can remove the comment for init method.

2022-01-28 02:05 UTC, ramesht007 reviewed
Good work !. Some minor changes then we are good to go.
Also fix the characters in a single line, according to PEP8 guide guidelines we can only have upto 79 character in a line.

2022-01-28 10:40 UTC, Kratos-is-here commented
Made the required changes in test.py.

2022-01-28 22:14 UTC, vkkhare requested changes

2022-01-28 22:14 UTC, vkkhare commented on test.py
> +
Why are there changes in the entire file?

2022-01-28 22:14 UTC, vkkhare commented on test.py
> +    Args:
Follow [Numpy style guide](https://numpydoc.readthedocs.io/en/latest/format.html)

Arguments not args

2022-01-31 20:15 UTC, Kratos-is-here commented
@vkkhare I have updated test.py

2022-02-07 08:43 UTC, closed without merging