testing for messages.py
NimbleEdge/RecoEdge pull request #143
Opened 2022-01-28 12:53 UTC by Yash-Vardhan-Sharma

## Description
Please include a summary of the change, the motivation, and any additional context that will help others understand your PR. If it closes one or more open issues, [please tag them as described here](https://help.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

## Relevant Issue
Issue #Tag the issue here

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/RecoEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/RecoEdge/blob/main/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/RecoEdge/labels)
- [ ] My changes are covered by tests

2022-01-28 22:07 UTC, vkkhare commented
You should fill the Issue template @Yash-Vardhan-Sharma for the PRs

2022-01-28 22:12 UTC, vkkhare requested changes

2022-01-28 22:12 UTC, vkkhare commented on test/test_messages.py
> +def test_jobresponse_status(job_type, senderid, receiverid):
dont just check the type, check their value as well

2022-01-28 22:12 UTC, vkkhare commented on test/test_messages.py
> +
check worker state as well

2022-01-28 22:12 UTC, vkkhare commented on test/test_messages.py
> +
run tests for Message class as well

2022-01-29 06:35 UTC, Yash-Vardhan-Sharma commented on test/test_messages.py
> +
done

2022-01-29 07:48 UTC, Yash-Vardhan-Sharma commented on test/test_messages.py
> +
done

2022-01-29 18:12 UTC, vkkhare commented on test/test_messages.py
> +
assertion is only for class type?

2022-01-29 19:39 UTC, vkkhare commented on test/test_messages.py
> +
Create a new method to test workerstate.

Also rebase once

2022-01-29 19:46 UTC, Yash-Vardhan-Sharma commented on test/test_messages.py
> +    assert obj.get_worker_state() == workerstate
@vkkhare this is the method to test workerstate output

2022-01-29 21:07 UTC, vkkhare commented
Rebase and I will merge then

2022-02-02 07:17 UTC, closed without merging