[WIP] Add Asynchronous messaging queue for send and receive functions
NimbleEdge/RecoEdge pull request #15
Opened 2021-07-25 09:33 UTC by ramesht007

This pull request is related to #8.

2021-07-25 15:19 UTC, ramesht007 commented
Hi,
I have added the necessary logic but I am not sure about the logic related to asyncio queue.
Please go through it.
Thanks

2021-07-25 16:14 UTC, vkkhare requested changes

2021-07-25 16:14 UTC, vkkhare commented on fedrec/communications/abstract_comm_manager.py
> +    def send(self):
Better rename it to send_message

2021-07-25 16:14 UTC, vkkhare commented on fedrec/communications/abstract_comm_manager.py
> +            print('Connecting to port . . . . ./n')
Check if subscriber is instantiated before sending

2021-07-25 16:14 UTC, vkkhare commented on fedrec/communications/abstract_comm_manager.py
> +            while True:
Why the message should be a class object? As in why “self”

2021-07-25 16:14 UTC, vkkhare commented on fedrec/communications/abstract_comm_manager.py
> +        def close(self):
Check before access

2021-07-25 16:14 UTC, vkkhare commented on fedrec/communications/abstract_comm_manager.py
> +            print("Connecting to Port . . . . ./n")
The connect call must be done in the init or after the first call for message. We should not connect everytime we call send message

2021-07-25 16:14 UTC, vkkhare commented on fedrec/communications/abstract_comm_manager.py
> +            while True:
I don’t think we need a loop here

2021-07-25 16:14 UTC, vkkhare commented on fedrec/communications/abstract_comm_manager.py
> +
Maybe also rename the file to something else?

2021-07-25 16:14 UTC, vkkhare commented on fedrec/communications/comm_manager.py
> +    async def rnd_sleep(t):
Dont need this

2021-07-25 16:14 UTC, vkkhare commented on fedrec/communications/comm_manager.py
> +        self.message_token = dict()
Why do we need message_token variable?

2021-07-25 16:14 UTC, vkkhare commented on fedrec/communications/comm_manager.py
> +        ZeroMQ.send(message)
This would actually be called as self.com_manager.send() instead of zeroMQ. We will create this inside init with registry.construct

2021-07-25 16:14 UTC, vkkhare commented on fedrec/communications/comm_manager.py
> +        queue = CommunicationStream.handle_message()
This queue should be instantiated on init and will be an asyncio Q

2021-07-25 16:14 UTC, vkkhare commented
Let me know if this helps clear the direction we have ti implement

2021-07-25 17:29 UTC, ramesht007 commented
ok, thanks will go through them

2021-07-25 17:30 UTC, ramesht007 commented on fedrec/communications/abstract_comm_manager.py
> +
any suggestions?

2021-07-25 17:37 UTC, ramesht007 commented on fedrec/communications/comm_manager.py
> +        self.message_token = dict()
For now I am storing the received message from queue in this foe further use.

2021-07-26 06:56 UTC, ramesht007 commented on fedrec/communications/comm_manager.py
> +        queue = CommunicationStream.handle_message()
this queue is the one that we are calling from the global communication manager and it contains the message token.

2021-07-26 06:59 UTC, ramesht007 commented on fedrec/communications/abstract_comm_manager.py
> +            while True:
ok removed from the class object

2021-07-26 17:20 UTC, vkkhare commented on fedrec/communications/abstract_comm_manager.py
> +
communication_interfaces

2021-07-26 17:20 UTC, vkkhare commented on fedrec/communications/comm_manager.py
> +        self.message_token = dict()
You don't need to do it, The guy implementing the messaging handler will do. You simply return the message

2021-07-26 17:20 UTC, vkkhare commented on fedrec/communications/comm_manager.py
> +        queue = CommunicationStream.handle_message()
yeah so global com manager will have the ZeroMQ q, this will be an asyncio q responsible for only storing the messages of the worker manager

2021-07-26 17:59 UTC, ramesht007 commented on fedrec/communications/abstract_comm_manager.py
> +
ok

2021-07-26 17:59 UTC, ramesht007 commented on fedrec/communications/comm_manager.py
> +        self.message_token = dict()
ok

2021-07-27 04:20 UTC, ramesht007 commented on fedrec/communications/abstract_comm_manager.py
> +
ok

2021-07-30 07:40 UTC, vkkhare requested changes

2021-07-30 07:40 UTC, vkkhare commented on fedrec/communications/communication_interfaces.py
> +                print('Connecting to port . . . . ./n')
This binding foe subscriber should also happen in init

2021-07-30 07:40 UTC, vkkhare commented on fedrec/communications/communication_interfaces.py
> +        async def handle_message(self):
This should be renamed to subscribe method. The continuous loop listens to new messages.

2021-07-30 07:40 UTC, vkkhare commented on fedrec/communications/global_comm_stream.py
> +    def handle_message(self):
The routing logic to worker manager comes here

2021-08-14 08:13 UTC, vkkhare commented on fedrec/communications/communication_interfaces.py
> +            if self.subscriber:
```python

def recieve_message(self):
      return self.subscriber.recv_pyobj()

```

Inside the global com stream
````python
while true ...
```

2021-08-14 08:14 UTC, vkkhare commented on fedrec/communications/global_comm_stream.py
> +        return queue
Add while true routing logic here

2021-08-17 11:42 UTC, vkkhare requested changes

2021-08-17 11:42 UTC, vkkhare commented on fedrec/communications/global_comm_stream.py
> +            worker_list = WorkerDataset()
the dataset should be initialised inside the init

2021-08-17 11:42 UTC, vkkhare commented on fedrec/communications/global_comm_stream.py
> +        self.subscriber = ZeroMQ.subscriber() # NOT ClEAR how to initolize subsrciber
```python
def __init__(self, config_dict):
    self.subscriber = registry.construct("communications", config_dict["communications"], is_subscriber=True)
```

2021-08-17 11:42 UTC, vkkhare commented on fedrec/communications/global_comm_stream.py
> +                message = self.Zmq.receive_message()
`self.subscriber.recieve_message()`

2021-08-17 11:42 UTC, vkkhare commented on fedrec/communications/global_comm_stream.py
> +        ZeroMQ.close()
`self.subscriber.close()`

2021-08-17 11:42 UTC, vkkhare commented on fedrec/federated_worker.py
> +    def send_message(self, message):
maybe rename this to `add_to_message_queue`

2021-08-17 11:42 UTC, vkkhare commented on fedrec/communications/communication_interfaces.py
> +    def send_message(self):
functions `close` and `recieve_message` should also be defined.

2021-08-17 11:42 UTC, vkkhare commented on fedrec/communications/global_comm_stream.py
>          self.message_stream = {} # TODO decide kafka stream or otherwise
not needed anymore

2021-08-17 13:52 UTC, ramesht007 commented on fedrec/communications/comm_manager.py
> +    async def send_message(self, message, block=False):
can you explain this?

2021-08-17 15:24 UTC, vkkhare commented on fedrec/communications/communication_interfaces.py
> +    def __init__(self, is_subscriber):
make default is_subscriber=False

2021-08-17 15:28 UTC, vkkhare commented on fedrec/communications/global_comm_stream.py
> +        self.Zmq = ZeroMQ()
not needed

2021-08-17 15:28 UTC, vkkhare commented on fedrec/communications/global_comm_stream.py
>          self.message_stream = {} # TODO decide kafka stream or otherwise
not needed

2021-08-17 15:29 UTC, vkkhare commented on fedrec/communications/global_comm_stream.py
> +    def handle_message(self):
should be an async call that keeps on running forever

2021-08-17 17:41 UTC, vkkhare approved these changes

2021-08-17 17:41 UTC, merged