Refactor serializer
NimbleEdge/RecoEdge pull request #155
Opened 2022-02-09 17:27 UTC by Yash-Vardhan-Sharma

## Description
wrote and update serializers

## Relevant Issue
Issue #Tag the issue here

## Affected Dependencies
List any dependencies that are required for this change.

## How has this been tested?
- Describe the tests that you ran to verify your changes.
- Provide instructions so we can reproduce.
- List any relevant details for your test configuration.

## Checklist
- [ ] I have followed the [Contribution Guidelines](https://github.com/NimbleEdge/RecoEdge/blob/main/CONTRIBUTING.md) and [Code of Conduct](https://github.com/NimbleEdge/RecoEdge/blob/main/CODE_OF_CONDUCT.md)
- [ ] I have commented my code following the [NimbleEdge Styleguide](https://numpydoc.readthedocs.io/en/latest/format.html)
- [ ] I have labeled this PR with the relevant [Type labels](https://github.com/NimbleEdge/RecoEdge/labels)
- [ ] My changes are covered by tests

2022-02-10 13:55 UTC, vkkhare commented on fedrec/serialization/abstract_serializer.py
>  from xml.dom import NotSupportedErr
update this line as well

2022-02-10 13:55 UTC, vkkhare commented on fedrec/serialization/job_response_serializer.py
> +                                  senderid,
it needs to serialise result as well

2022-02-14 19:01 UTC, ramesht007 commented on fedrec/serialization/trainer_state_serializer.py
> +        response_dict["state_dict"] = self.serialize_attribute(
Write serializer for state dict

2022-02-14 19:01 UTC, ramesht007 commented on fedrec/serialization/trainer_state_serializer.py
> +            obj['state_dict'])
same as above, write deserializer

2022-02-14 19:01 UTC, ramesht007 commented on fedrec/serialization/trainer_state_serializer.py
> +        model_preproc = self.deserialize_attribute(
same as above, write deserializer

2022-02-14 19:01 UTC, ramesht007 commented on fedrec/serialization/trainer_state_serializer.py
> +        local_sample_number = self.deserialize_attribute(
don't need to deserialize, we can send it directly

2022-02-15 12:44 UTC, vkkhare requested changes

2022-02-15 12:44 UTC, vkkhare commented on fedrec/serialization/aggregator_state_serializer.py
> +
call json.parse first before deserializing to get the object dictionary

2022-02-15 12:44 UTC, vkkhare commented on fedrec/serialization/job_response_serializer.py
> +        response_dict["senderid"] = self.serialize_attribute(
These don't need to be serialized/ deserialized. The ids are string or int

2022-02-15 12:44 UTC, vkkhare commented on fedrec/serialization/job_response_serializer.py
> +        senderid = self.deserialize_attribute(obj['senderid'])
parse from serialization strategy first

2022-02-15 12:44 UTC, vkkhare commented on fedrec/serialization/trainer_state_serializer.py
> +
parse from serializaiton strategy first

2022-02-15 13:03 UTC, Yash-Vardhan-Sharma commented on fedrec/serialization/aggregator_state_serializer.py
> +
done

2022-02-15 13:04 UTC, Yash-Vardhan-Sharma commented on fedrec/serialization/job_response_serializer.py
> +        senderid = self.deserialize_attribute(obj['senderid'])
done

2022-02-15 13:04 UTC, Yash-Vardhan-Sharma commented on fedrec/serialization/trainer_state_serializer.py
> +
done

2022-02-17 09:47 UTC, merged