[WIP] Message Class
NimbleEdge/RecoEdge pull request #19
Opened 2021-09-25 17:23 UTC by ramesht007

Work In Process

- [ ] yet to implement process manager id
- [ ] cross check for methods

2021-09-25 18:19 UTC, vkkhare requested changes

2021-09-25 18:19 UTC, vkkhare commented on fedrec/communications/messages.py
> +        return self.senderid
Why are they abstract methods?

2021-09-25 18:19 UTC, vkkhare commented on fedrec/communications/messages.py
> +class JobSubmission(Message):
Renaming this to JobSubmitMessage is better

2021-09-25 18:19 UTC, vkkhare commented on fedrec/communications/messages.py
> +class train_JobSubmission(JobSubmission):
Why do we need different classes for train, test and jobs?

2021-09-25 18:19 UTC, vkkhare commented on fedrec/communications/messages.py
> +class get_model(Message):
These shouldn't be a class but a method in the workers

2021-09-25 18:19 UTC, vkkhare commented on fedrec/communications/messages.py
> +class send_model(Message):
Same here

2021-09-25 18:19 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +            trainer=base_trainer, id=worker_index, config_dict=com_dict)
Worker com manager cannot instantiate itself

2021-09-25 18:19 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> -            message = Message(MyMessage.MSG_TYPE_JOB_TRAIN, self.get_sender_id())
In this case we can simply pass job type as an argument since everything else is same

2021-09-25 18:19 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +            message = test_JobSubmission(self.id, receive_id, json.dumps(FederatedWorker.serialise()))
Use ProcMessageType for job type basically an enum class

2021-09-25 18:19 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +        self.fl_com_manager.queue.put(message)
You can simply access, self.queue now

2021-09-26 02:16 UTC, ramesht007 commented on fedrec/communications/worker_manager.py
> +            message = test_JobSubmission(self.id, receive_id, json.dumps(FederatedWorker.serialise()))
one thing more will training and testing messages have some separate methods or some difference?

2021-09-26 02:16 UTC, ramesht007 commented on fedrec/communications/worker_manager.py
> +        self.fl_com_manager.queue.put(message)
ok, Noted

2021-09-26 03:03 UTC, ramesht007 commented on fedrec/communications/messages.py
> +class train_JobSubmission(JobSubmission):
I thought there would be some different parameters for them.
Will remove

2021-09-26 03:31 UTC, ramesht007 commented on fedrec/communications/worker_manager.py
> +            message = test_JobSubmission(self.id, receive_id, json.dumps(FederatedWorker.serialise()))
Can you give a short example of ProcMessageType.
I am thinking of something like this ....
`class ProcMessage(Enum):
    SYNC_MODEL = 1
    TRAIN_JOB = auto()
    TEST_JOB = auto()`

and for JobType message :
`def send_job(self, receive_id, ProcMessage.TRAIN_JOB`

2021-09-26 03:39 UTC, ramesht007 commented on fedrec/communications/messages.py
> +class get_model(Message):
ok

2021-09-26 07:21 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +            message = test_JobSubmission(self.id, receive_id, json.dumps(FederatedWorker.serialise()))
Looks good

2021-09-26 07:22 UTC, ramesht007 commented on fedrec/communications/worker_manager.py
> +            message = test_JobSubmission(self.id, receive_id, json.dumps(FederatedWorker.serialise()))
cool

2021-09-26 07:34 UTC, vkkhare requested changes

2021-09-26 07:34 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +        self.queue = asyncio.Queue()
The queue is already a part of communication manager

2021-09-26 07:34 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +    def add_to_message_queue(self, message):
I think we can put this in Communication Manager super class. Since it has the queue and the method is general for everyone

2021-09-26 07:34 UTC, vkkhare commented on fedrec/communications/worker_manager.py
>          self.send_message(message)
Typo

2021-09-26 07:34 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +        self.recieverid = ''
Self.id is your sender id. Why do you need a global reciever id, this will change in every message

2021-09-26 07:34 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +            message = JobSubmitMessage(self.id, receive_id)
Shouldn't it have JobType enum as an argument

2021-09-26 07:34 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +        self.recieverid = message.get_sender_id()
Why is this needed?

2021-09-26 07:34 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +        message.add_modelweights(weights)
Instead of calling `add` method for each, you can directly pass all of them into constructor. That way we can also check of anything is not defined.

2021-09-26 07:34 UTC, vkkhare commented on fedrec/communications/messages.py
> +        return self.receiverid
There should be 4 classes

JobSubmitMessage for job submission
JobResponseMessage for corresponding response

ModelRequestMessage for requesting model
ModelResponseMessage for corresponding response

2021-09-26 07:36 UTC, ramesht007 commented on fedrec/communications/worker_manager.py
> +    def add_to_message_queue(self, message):
okay

2021-09-26 07:36 UTC, ramesht007 commented on fedrec/communications/worker_manager.py
>          self.send_message(message)
ohh LOL :)

2021-09-26 07:39 UTC, ramesht007 commented on fedrec/communications/worker_manager.py
> +        self.recieverid = ''
yes the thing is sender is okay and the for the one we have to send message we can provide receiver id.
But for the messages that we have to return back. We can just use the sender_id from receiver to return the message.

2021-09-26 07:39 UTC, ramesht007 commented on fedrec/communications/worker_manager.py
> +        self.recieverid = message.get_sender_id()
yes the thing is sender is okay and the for the one we have to send message we can provide receiver id.
But for the messages that we have to return back. We can just use the sender_id from receiver to return the message.

2021-09-26 07:40 UTC, ramesht007 commented on fedrec/communications/worker_manager.py
> +            message = JobSubmitMessage(self.id, receive_id)
will commit in next batch of changes

2021-09-26 07:49 UTC, ramesht007 commented on fedrec/communications/worker_manager.py
> +        message.add_modelweights(weights)
ok

2021-09-26 09:06 UTC, ramesht007 commented on fedrec/communications/global_comm_stream.py
> +
Still not sure about this?
how it will go through

2021-09-26 09:11 UTC, vkkhare requested changes

2021-09-26 09:11 UTC, vkkhare commented on fedrec/communications/messages.py
> +    def __init__(self, senderid):
This would also need receiver id

2021-09-26 09:11 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +        self.queue = asyncio.Queue()
Not needed. Remove it now

2021-09-26 09:11 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +        if job_type == ProcMessage.TRAIN_JOB.name:
You can check enums equality directly without names. Assume that is what will be passed in jobtype argument

2021-09-26 09:11 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +            message = JobSubmitMessage(self.id, receive_id, json.dumps(FederatedWorker.serialise()))
You will need to pass jobtype as an argument so that process manager understands what kind of job it is

2021-09-26 19:44 UTC, vkkhare requested changes

2021-09-26 19:44 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +    def receive_message(self, message):
Why is this method needed?

2021-09-26 19:44 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +        message.aadd_local_sample_num(local_sample_num)
Pass all these parameters in the constructor

2021-09-26 19:44 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +        self.receiverid = ''
Not needed

2021-09-27 02:23 UTC, ramesht007 commented on fedrec/communications/worker_manager.py
> +        message.aadd_local_sample_num(local_sample_num)
Forgot to remove this. Sorry

2021-09-27 02:23 UTC, ramesht007 commented on fedrec/communications/worker_manager.py
> +    def receive_message(self, message):
ok

2021-09-27 04:54 UTC, vkkhare requested changes

2021-09-27 04:54 UTC, vkkhare commented on fedrec/communications/worker_manager.py
> +        self.queue = asyncio.Queue()
Don't need this queue as well

2021-09-27 04:54 UTC, vkkhare commented on fedrec/communications/worker_manager.py
>          elif job_type == 'test':
It's better to write this as 

```python

if job_type == ProcMessage.TRAIN_JOB
     message = ...
```

2021-09-27 04:54 UTC, vkkhare commented on fedrec/communications/messages.py
> +        if job_type == 'train':
simply pass job_type as enum.

```python
self.job_type = job_type
```

2021-09-27 05:13 UTC, vkkhare approved these changes

2021-09-27 05:14 UTC, merged