Added Documentation for MPI Process Class
NimbleEdge/RecoEdge pull request #36
Opened 2021-11-02 07:43 UTC by kavinotravi

#27 
Added Documentation to MPIProcess Class

2021-11-11 11:26 UTC, vkkhare requested changes

2021-11-11 11:26 UTC, vkkhare commented on fedrec/multiprocessing/mpi_process.py
> +    """
We need to add documentation for `run`. and `publish` methods as well. Also Base Trainer isn't a class anymore, it will be Trainer in Actors

2021-11-13 09:56 UTC, kavinotravi commented on fedrec/multiprocessing/mpi_process.py
> +    """
@vkkhare, Added Documentation for run and publish method

2021-11-14 07:37 UTC, vkkhare approved these changes

2021-11-14 07:37 UTC, merged