Serialize, Deserialize torch.tensor
NimbleEdge/RecoEdge pull request #44
Opened 2021-11-14 09:08 UTC by ruchirgarg05

Added support for serializing and deserializing tensor object, by saving it to file and passing the file as string object

ref: Issue#37

2021-11-14 09:58 UTC, vkkhare requested changes

2021-11-14 09:58 UTC, vkkhare commented on fedrec/utilities/serialization.py
> +    if is_s3_file(obj):
move this logic to a seperate method. Just check if it is a `tensor` here and call a method to load it from S3 or otherwiese

2021-11-14 09:58 UTC, vkkhare commented on fedrec/utilities/serialization.py
> +    param obj: It can be a file containing tensor the file maybe stream file or a file path or serialized pkl string.
there can be multiple types of objects that need deserialization, tensor, dictionaries, numpy arrays, pyarray etc. 

`deserialize_object` must check for the type and based on that call a relevant deserialization method. You can pass on the `type` as an argument to deserialize_object. We will get the type via a call to URL or method description.

2021-11-14 09:58 UTC, vkkhare commented on fedrec/utilities/serialization.py
> +            save_tensor(obj, file)
return the response

2021-11-14 09:58 UTC, vkkhare commented on fedrec/utilities/serialization.py
> +def copy_s3_file(self, file):
maybe rename this to download_file. This method should be in saver_utils

2021-11-14 09:58 UTC, vkkhare commented on fedrec/utilities/serialization.py
> +    """
A better way to do this would be create a serialization folder in fedrec that defines various classes and their associated serializers/deserializers. That way we will have all the logic concentrated and easy to edit in the longer run.

2021-11-16 14:41 UTC, abhigarg-iitk commented on fedrec/utilities/serialization.py
NI : I think the top level function should have 2 blank [lines](https://www.python.org/dev/peps/pep-0008/#blank-lines)

2021-11-16 14:46 UTC, abhigarg-iitk commented on fedrec/utilities/serialization.py
> +        from urlparse import urlparse
NI : I think it might be better to use global imports. Especially for [core libs](https://stackoverflow.com/questions/1024049/is-it-pythonic-to-import-inside-functions)

2021-11-16 14:50 UTC, abhigarg-iitk commented on fedrec/utilities/serialization.py
> +    """
yes I think this might be good :-

a base abstract class with just 3 functions:- Init, serialize, deserialize...... And then object specific class. ANd here just call serialize and deserialize.

2021-11-16 14:52 UTC, abhigarg-iitk commented on fedrec/utilities/serialization.py
> +    param file: This can either be a local file storage system or a file to be stored in the s3 clod.
NI : clod --> Cloud

2021-11-17 16:21 UTC, vkkhare commented on fedrec/utilities/serialization.py
> +from fedrec.serialization.serializers import SerializeDeserializeTensor
you can simply name it as TensorSerializer (shorter ;p)

2021-11-17 16:21 UTC, vkkhare commented on fedrec/serialization/serializers.py
> +            # if file is provided, save the tesor to the file and return the file path.
typo in tensor

2021-11-17 16:21 UTC, vkkhare commented on fedrec/serialization/serializers.py
> +        self.obj = obj
why does it need to store the object reference? You can simply make the methods static and pass object in the argument

2021-11-17 16:21 UTC, vkkhare commented on fedrec/serialization/serializers.py
> +#TODO: For objects if the serialization takes a substantial amount of data
is it still TODO? seems like it is already implemented

2021-11-17 16:21 UTC, vkkhare commented on fedrec/serialization/serializers.py
> +SERIALIZER_REGISTRY[torch.tensor] = SerializerDeserializerTensor
should use class name for registry.

2021-11-17 16:21 UTC, vkkhare commented on fedrec/serialization/serializers.py
> +SERIALIZER_REGISTRY = {}
you can simply use registry module with kind 'serializer' and name as class name.

```python
@registry.load('serializer', Tensor.__name__)
```

2021-11-17 16:21 UTC, vkkhare commented on fedrec/utilities/serialization.py
> +        return SerializeDeserializeTensor(obj).serialize(file)
better to use registry here.

2021-11-19 10:26 UTC, vkkhare commented on fedrec/serialization/serializers.py
> +class AbstractSerializerDeserializer(ABC):
rename this as well

2021-11-19 10:26 UTC, vkkhare commented on fedrec/serialization/serializers.py
> +@registry.load("serializer", "tensor")
instead of writing "tensor", you can use `Tensor.__name__` to avoid issues with classes

2021-11-19 10:26 UTC, vkkhare commented on fedrec/utilities/serialization.py
> +        return registry.lookup("serializer", "tensor").serialize(obj, file)
this can simply become 
```python
registry.lookup("serializer",torch.Tensor.__class__).serialize(obj, file)
```

2021-11-19 10:26 UTC, vkkhare commented
Also @ruchirgarg05 rebase the branch so that it is mergeable

2021-11-20 07:02 UTC, closed without merging