Added: Documentation for Serializers
NimbleEdge/RecoEdge pull request #64
Opened 2021-12-25 22:27 UTC by divyanshugit

This PR resolves issue #59.

- [x] Added the inline documentation for Serializers.

2021-12-25 22:32 UTC, vkkhare requested changes

2021-12-25 22:32 UTC, vkkhare commented on fedrec/serialization/serializers.py
> +        Serializes an JSON object.
Serializes a python object to json

2021-12-25 22:32 UTC, vkkhare commented on fedrec/serialization/serializers.py
> +    JSONSerializer serializes and deserializes json objects.
Uses json serialization strategy for objects

2021-12-26 04:14 UTC, ramesht007 reviewed
In Json deserialize I think we can also add

Deserializes a JSON object and adds to registry based on `__type__` key.

2021-12-26 08:08 UTC, vkkhare commented on fedrec/serialization/serializers.py
> +        Generates a dictionary from an object.
appends type information for finding the appropriate serialiser

2021-12-26 11:43 UTC, vkkhare requested changes

2021-12-26 11:43 UTC, vkkhare commented on fedrec/serialization/serializers.py
> +        Deserializes a JSON object and adds to registry based on `__type__` key.
It does not add to registry rather fetches the correct serializer from registry based on __type__

2021-12-26 15:00 UTC, vkkhare approved these changes

2021-12-26 15:00 UTC, ramesht007 commented
Well done @divyanshugit !!

2021-12-26 15:03 UTC, merged