Added: Inline Documentation for Kafka Interfaces
NimbleEdge/RecoEdge pull request #67
Opened 2021-12-26 15:19 UTC by divyanshugit

This PR resolves issue #52 

- [x] Added the inline documentation for Kafka Interfaces

2021-12-26 15:28 UTC, ramesht007 commented on fedrec/communications/kafka_interfaces.py
> +        The consumer to use.
this can be:
intimate consumer at the initialisation of the class.

2021-12-26 15:28 UTC, ramesht007 commented on fedrec/communications/kafka_interfaces.py
> +    producer: KafkaProducer
So the consumer and producer both will be initiated, if the argument is True. If one them is marked false then they will not be initiated.

2021-12-26 15:28 UTC, ramesht007 commented on fedrec/communications/kafka_interfaces.py
> +        The url of the consumer.
This can be:
The url to which the consumer will listen for the message from the producer

2021-12-26 15:28 UTC, ramesht007 commented on fedrec/communications/kafka_interfaces.py
> +    consumer_port: int
The port to which the consumer will be connected

2021-12-26 15:28 UTC, ramesht007 commented on fedrec/communications/kafka_interfaces.py
> +    producer_url: str
This can be:
The url to which producer will be connect to add message to kafka.

2022-01-04 04:03 UTC, ramesht007 commented on fedrec/communications/kafka_interfaces.py
> +        URL to which producer will send the message token to kafka broker.
Same as above ```consumer URL```

2022-01-04 04:03 UTC, ramesht007 commented on fedrec/communications/kafka_interfaces.py
> +        The port to which producer will connect to send the message token to kafka broker.
Same as above ```Consumer Port```

2022-01-04 04:03 UTC, ramesht007 commented on fedrec/communications/kafka_interfaces.py
> +        Topic to which producer will send the message token to kafka broker.
read about kafka topics [here](https://dattell.com/data-architecture-blog/what-is-a-kafka-topic/#:~:text=Kafka%20topics%20are%20the%20categories,consumers%20read%20data%20from%20topics.)

2022-01-05 13:41 UTC, ramesht007 commented on fedrec/communications/kafka_interfaces.py
> +        URL to which consumer will connects to get the message token.
it should be ```will connect```

2022-01-05 13:41 UTC, ramesht007 commented on fedrec/communications/kafka_interfaces.py
> +        URL to which consumer will connects to send the message token.
it should be ```will connect```

2022-01-05 13:41 UTC, ramesht007 commented on fedrec/communications/kafka_interfaces.py
> +        Topic to which producer will subscribe to send the message
it can be :
```The topic to which producer will subscribe to send message token to consumer subscribed to that topic.```

2022-01-05 13:42 UTC, ramesht007 commented
Some Minor changes then we are ready to go!!

2022-01-05 14:05 UTC, ramesht007 approved these changes
LGTM!

2022-01-05 14:25 UTC, vkkhare requested changes

2022-01-05 14:25 UTC, vkkhare commented on fedrec/communications/kafka_interfaces.py
> +       Consumer will get the message token form kafka broker.
from kafka broker

2022-01-05 14:25 UTC, vkkhare commented on fedrec/communications/kafka_interfaces.py
> +    Kafka specific methods below here. These are not part of the
It's better to write it as:

Implements the basic send/receive interface so that workers and the job executor can communicate with each other.

2022-01-05 14:25 UTC, vkkhare commented on fedrec/communications/kafka_interfaces.py
> +        URL to which consumer will connects to get the message token.
*connect

2022-01-05 14:25 UTC, vkkhare commented on fedrec/communications/kafka_interfaces.py
> +        Port where the consumer connect to get token.
*connects

2022-01-05 14:25 UTC, vkkhare commented on fedrec/communications/kafka_interfaces.py
> +        Topic to which consumer will subscribe to get the message
the consumer topic refers to the topic from which the consumer fetches its messages.

2022-01-05 14:25 UTC, vkkhare commented on fedrec/communications/kafka_interfaces.py
> +        URL to which consumer will connect to send the message token.
producer*

2022-01-05 14:25 UTC, vkkhare commented on fedrec/communications/kafka_interfaces.py
> +        Topic to which producer will subscribe to send message token
Topic to which producer will subscribe to send message token

2022-01-05 14:25 UTC, vkkhare commented on fedrec/communications/kafka_interfaces.py
> +        Receives a message from the consumer.
from the kafka broker

2022-01-05 14:25 UTC, vkkhare commented on fedrec/communications/kafka_interfaces.py
> +        Sends a message to the producer.
kafka broker

2022-01-06 04:07 UTC, vkkhare approved these changes

2022-01-06 04:08 UTC, merged