Update issue templates
NimbleEdge/RecoEdge pull request #72
Opened 2021-12-27 16:31 UTC by ramesht007

2022-01-05 13:35 UTC, ramesht007 commented
Ready to merge!!

2022-01-06 06:44 UTC, vkkhare requested changes

2022-01-06 06:44 UTC, vkkhare commented on .github/ISSUE_TEMPLATE/documentation.yml
> +      description: "Please go throught [PEP8](https://numpydoc.readthedocs.io/en/latest/format.html) guildlines before starting."
thorugh* and pep8 guidelines could be found [here](https://www.python.org/dev/peps/pep-0008/)

The numpy doc link is for how to write documentation.

2022-01-06 06:51 UTC, vkkhare approved these changes

2022-01-06 06:51 UTC, ramesht007 commented on .github/ISSUE_TEMPLATE/documentation.yml
> +      description: "Please go throught [PEP8](https://numpydoc.readthedocs.io/en/latest/format.html) guildlines before starting."
done

2022-01-06 06:58 UTC, merged